INSERT INTO articles (slug, title, summary, tags, accent, read_time, content, published, created_at, updated_at)
VALUES
(
  'go-concurrency-patterns',
  'Go Concurrency Patterns',
  'Real-world goroutines, channels and select examples. How to not break production while squeezing every bit out of a multicore CPU.',
  ARRAY['Go', 'Concurrency', 'Backend'],
  'cyan',
  8,
  '[
    {"type":"h2","text":"Why Concurrency in Go Feels Different"},
    {"type":"paragraph","text":"Go''s concurrency model is built around goroutines and channels. Unlike threads, goroutines are cheap — you can spawn thousands without breaking a sweat. The runtime schedules them across available OS threads automatically."},
    {"type":"h2","text":"Goroutine Leaks"},
    {"type":"paragraph","text":"The most common mistake: launching a goroutine that blocks forever because nobody drains its channel. Use context cancellation or a done channel to always give goroutines a way out."},
    {"type":"code","lang":"go","text":"func leak() {\n    ch := make(chan int)\n    go func() {\n        ch <- 42 // blocks forever — nobody reads\n    }()\n}\n\nfunc safe(ctx context.Context) {\n    ch := make(chan int, 1)\n    go func() {\n        select {\n        case ch <- 42:\n        case <-ctx.Done():\n        }\n    }()\n}"},
    {"type":"h2","text":"The Select Statement"},
    {"type":"paragraph","text":"select lets a goroutine wait on multiple channels at once. Add a default case to make it non-blocking. It''s the foundation of timeouts, cancellation, and fan-in patterns."},
    {"type":"code","lang":"go","text":"select {\ncase msg := <-ch:\n    fmt.Println(msg)\ncase <-ctx.Done():\n    return ctx.Err()\ndefault:\n    // no message ready, move on\n}"},
    {"type":"h2","text":"Worker Pools"},
    {"type":"paragraph","text":"A fixed number of goroutines pulling jobs off a channel. Controls resource usage and avoids spawning unbounded goroutines under load."},
    {"type":"code","lang":"go","text":"jobs := make(chan Job, 100)\nvar wg sync.WaitGroup\n\nfor i := 0; i < 4; i++ {\n    wg.Add(1)\n    go func() {\n        defer wg.Done()\n        for j := range jobs {\n            process(j)\n        }\n    }()\n}\n\nfor _, j := range allJobs {\n    jobs <- j\n}\nclose(jobs)\nwg.Wait()"},
    {"type":"h2","text":"Pipeline Pattern"},
    {"type":"paragraph","text":"Chain stages together where each stage reads from the previous channel and writes to the next. Each stage is a goroutine. Clean separation of concerns, easy to test."},
    {"type":"code","lang":"go","text":"func generate(nums ...int) <-chan int {\n    out := make(chan int)\n    go func() {\n        defer close(out)\n        for _, n := range nums {\n            out <- n\n        }\n    }()\n    return out\n}\n\nfunc square(in <-chan int) <-chan int {\n    out := make(chan int)\n    go func() {\n        defer close(out)\n        for n := range in {\n            out <- n * n\n        }\n    }()\n    return out\n}"}
  ]'::jsonb,
  true,
  '2026-04-15T00:00:00Z',
  '2026-04-15T00:00:00Z'
),
(
  'postgres-indexing-guide',
  'PostgreSQL: Indexes That Actually Work',
  'EXPLAIN ANALYZE, B-tree vs GIN vs BRIN, partial and composite indexes. How to turn a 3-second query into 3 milliseconds.',
  ARRAY['PostgreSQL', 'Database', 'Performance'],
  'purple',
  11,
  '[
    {"type":"h2","text":"Start with EXPLAIN ANALYZE"},
    {"type":"paragraph","text":"Before adding any index, run EXPLAIN ANALYZE on your slow query. Look at the Seq Scan nodes — those are your targets. Never add indexes blindly."},
    {"type":"code","lang":"sql","text":"EXPLAIN ANALYZE\nSELECT * FROM orders\nWHERE user_id = 42 AND status = ''pending''\nORDER BY created_at DESC;"},
    {"type":"h2","text":"B-tree: The Default"},
    {"type":"paragraph","text":"B-tree is the default and covers 90% of cases. Use it for equality, ranges, sorting, and LIKE patterns that start with a literal (not %wildcard)."},
    {"type":"code","lang":"sql","text":"CREATE INDEX idx_orders_user_status\n    ON orders(user_id, status);\n\nCREATE INDEX idx_orders_created\n    ON orders(created_at DESC);"},
    {"type":"h2","text":"Partial Indexes"},
    {"type":"paragraph","text":"Index only the rows you actually query. A partial index on active or pending rows is dramatically smaller and faster than a full-table index."},
    {"type":"code","lang":"sql","text":"CREATE INDEX idx_orders_pending\n    ON orders(user_id, created_at)\n    WHERE status = ''pending'';\n\n-- Only ~2% of rows, index is tiny and fits in cache"},
    {"type":"h2","text":"GIN for Arrays and JSONB"},
    {"type":"paragraph","text":"B-tree cannot index array elements or JSONB keys. GIN (Generalized Inverted Index) builds an inverted index over all values inside a document or array."},
    {"type":"code","lang":"sql","text":"CREATE INDEX idx_articles_tags ON articles USING GIN(tags);\n\n-- Now this is fast:\nSELECT * FROM articles WHERE tags @> ARRAY[''Go''];"},
    {"type":"h2","text":"Composite Index Column Order"},
    {"type":"paragraph","text":"Put the most selective column first, then equality conditions before range conditions. A composite index (a, b) supports queries on a alone, but not b alone."},
    {"type":"code","lang":"sql","text":"-- Query: WHERE user_id = $1 AND created_at > $2\n-- Correct order:\nCREATE INDEX ON orders(user_id, created_at);\n\n-- Wrong order (range column first blocks equality use):\nCREATE INDEX ON orders(created_at, user_id); -- suboptimal"}
  ]'::jsonb,
  true,
  '2026-04-02T00:00:00Z',
  '2026-04-02T00:00:00Z'
),
(
  'react-performance-tricks',
  'React: Performance Without Pain',
  'memo, useMemo, useCallback — when they actually help and when they just get in the way. Profiling with DevTools and real scenarios.',
  ARRAY['React', 'Frontend', 'Performance'],
  'orange',
  7,
  '[
    {"type":"h2","text":"Profile Before Optimizing"},
    {"type":"paragraph","text":"Open React DevTools Profiler, record an interaction, and look at which components rendered. Optimize only the ones that show up as expensive and frequent. Most apps never need memo."},
    {"type":"h2","text":"React.memo"},
    {"type":"paragraph","text":"Wrapping a component in memo skips re-render if props haven''t changed (shallow comparison). Only worth it when the parent re-renders frequently and the child is expensive to render."},
    {"type":"code","lang":"jsx","text":"const ArticleCard = memo(function ArticleCard({ article }) {\n    return <div>{article.title}</div>\n})\n\n// Pointless if the parent rarely re-renders\n// Pointless if props include new object refs every time"},
    {"type":"h2","text":"useMemo"},
    {"type":"paragraph","text":"Memoizes a computed value. Useful for expensive calculations on large arrays. Not useful for simple transforms — the overhead of useMemo itself may exceed the savings."},
    {"type":"code","lang":"jsx","text":"// Worth it: sorting 10k items\nconst sorted = useMemo(\n    () => [...items].sort(compareFn),\n    [items]\n)\n\n// Not worth it:\nconst label = useMemo(() => `Hello ${name}`, [name])"},
    {"type":"h2","text":"useCallback"},
    {"type":"paragraph","text":"Stabilizes a function reference across renders. Only matters when passing callbacks to memo-wrapped children or as useEffect dependencies."},
    {"type":"code","lang":"jsx","text":"const handleClick = useCallback((id) => {\n    dispatch({ type: ''SELECT'', id })\n}, [dispatch])\n\n// Without useCallback, memo on the child is useless:\n// every render creates a new function reference"},
    {"type":"h2","text":"Key Insight"},
    {"type":"paragraph","text":"The React team''s own advice: write code without these hooks first. Add them only after profiling shows a real problem. Premature memoization adds complexity and can actually slow things down if dependencies change every render anyway."}
  ]'::jsonb,
  true,
  '2026-03-20T00:00:00Z',
  '2026-03-20T00:00:00Z'
),
(
  'dsa-graphs-bfs-dfs',
  'Graphs: BFS, DFS and When to Use Which',
  'Breadth-first and depth-first traversal — the foundation of graph algorithms. Breaking it down with LeetCode problems and real-world scenarios.',
  ARRAY['DSA', 'Algorithms', 'Go'],
  'green',
  10,
  '[
    {"type":"h2","text":"Graph Representation"},
    {"type":"paragraph","text":"An adjacency list is almost always the right choice. It uses O(V + E) memory and iterating neighbors is O(degree). An adjacency matrix uses O(V²) and is only worth it for dense graphs where you need O(1) edge existence checks."},
    {"type":"code","lang":"go","text":"type Graph struct {\n    adj map[int][]int\n}\n\nfunc (g *Graph) AddEdge(u, v int) {\n    g.adj[u] = append(g.adj[u], v)\n    g.adj[v] = append(g.adj[v], u) // undirected\n}"},
    {"type":"h2","text":"BFS — Breadth-First Search"},
    {"type":"paragraph","text":"BFS explores level by level using a queue. It finds the shortest path in an unweighted graph. Use it when you need the minimum number of steps to reach a target."},
    {"type":"code","lang":"go","text":"func BFS(g *Graph, start int) []int {\n    visited := map[int]bool{start: true}\n    queue   := []int{start}\n    order   := []int{}\n\n    for len(queue) > 0 {\n        node := queue[0]\n        queue = queue[1:]\n        order = append(order, node)\n\n        for _, neighbor := range g.adj[node] {\n            if !visited[neighbor] {\n                visited[neighbor] = true\n                queue = append(queue, neighbor)\n            }\n        }\n    }\n    return order\n}"},
    {"type":"h2","text":"DFS — Depth-First Search"},
    {"type":"paragraph","text":"DFS goes as deep as possible before backtracking. Use it for cycle detection, topological sort, connected components, and tree problems. The recursive version is clean; the iterative version uses an explicit stack."},
    {"type":"code","lang":"go","text":"func DFS(g *Graph, node int, visited map[int]bool, order *[]int) {\n    visited[node] = true\n    *order = append(*order, node)\n\n    for _, neighbor := range g.adj[node] {\n        if !visited[neighbor] {\n            DFS(g, neighbor, visited, order)\n        }\n    }\n}"},
    {"type":"h2","text":"When to Use Which"},
    {"type":"paragraph","text":"BFS: shortest path in unweighted graphs, level-order traversal, finding nearest node matching a condition. DFS: cycle detection, topological sort, detecting connected components, maze solving, backtracking problems."},
    {"type":"h2","text":"Topological Sort with DFS"},
    {"type":"paragraph","text":"Process nodes in dependency order. After fully exploring a node (all descendants done), push it onto a stack. The stack gives you reverse topological order."},
    {"type":"code","lang":"go","text":"func topoSort(g *Graph, node int, visited map[int]bool, stack *[]int) {\n    visited[node] = true\n    for _, neighbor := range g.adj[node] {\n        if !visited[neighbor] {\n            topoSort(g, neighbor, visited, stack)\n        }\n    }\n    *stack = append(*stack, node) // add after all descendants\n}"}
  ]'::jsonb,
  true,
  '2026-03-05T00:00:00Z',
  '2026-03-05T00:00:00Z'
)
ON CONFLICT (slug) DO NOTHING;
